---
device: cpu
model:
    parameters:
        in_channels: 2
        out_channels: 2
        spatial_dims: 2
        channels: (16, 32, 64, 128, 256)
        strides: (2, 2, 2, 2)
        num_res_units: 2
        dropout: 0.2
optimizer:
    lr: 1e-3
    weight_decay: 1e-5
    amsgrad: True
BATCH_SIZE_TRAIN: 128
BATCH_SIZE_VAL: 64